### ISSUE TITLE
[wayland-server] Dispatch won't call my impl handlers

### ISSUE THREAD

**Issue by ripread** [vberger/wayland-rs#103] opened 2017-04-10 03:43 UTC
I've registered a global wl_compositor handler and thus have impl'd bind for that global, however my bind implementation never gets called. In my client code I the register_global callback gets  alled for wl_compositor so I know my code registering the global works. In the client code I then make a call to wl_registry_bind and while the eventloop never receives an event and my bind function is never called, the wl_registry_bind does return a pointer.  

I've simply followed your examples on the server documentation page, can you think of anything that might be causing this?

**Comment by vberger** [comment] 2017-04-10 05:05
It's be best if you could link here an small example code that reproduce your issue (both the server & client side), without that I can only make guesses.

From what you describe, my first guess would be that it seems events/requests are not properly being dispatched between the client and server. Are you properly sending the messages client-side? As the protocol is asynchronous, `wl_registry_bind` will return a pointer even if the message was actually not yet sent to the server. To make sure messages are sent, you need to call `WlDisplay::flush` in your event loop, or often `WlDisplay::sync_roundtrip()` is used during the initialization phase of the client.

**Comment by ripread** [comment] 2017-04-10 18:53
https://gist.github.com/ripread/6e7d683e2ccf2b79828073cb0a35a99e
I compiled the client code with `gcc -lwayland-client main.c` 

The server code receives an event when the display is connected, when roundtrip is called, and then when the client code halts and the display is disconnected. No event is received when registry_bind is called.

**Comment by vberger** [comment] 2017-04-10 19:09
I see, this is you client code that has an issue: you need to call `sync_roundtrip(display)` twice.

The first time will fetch the registry events call your `registry_global` handler, which instantiates the compositor and buffer the request in the client's output buffer, but not actually send it.

The second time will actually send the event to the compositor.

**Comment by ripread** [comment] 2017-04-10 19:38
So I added a roundtrip to the end of `registry_global` and it works now :D. That being said, the actual client code works in Weston and only calls roundtrip the one time. Do you know what Weston does differently?

BTW, thanks for helping a newbie out!

**Comment by vberger** [comment] 2017-04-10 20:06
This is because the `wl_display_dispatch` function flushes pending requests to the compositor, so the first time you enter your event loop, all the pending requests your program had prepared are send to the compositor that then processes them.

Al this message passing is completely handled by libwayland-client and libwayland-server, there is nothing specific to weston in there. :)

**Comment by vberger** [comment] 2017-04-12 10:36
I guess I can close this? Feel free to reopen if your issue is not solved.

**Closed by vberger** 2017-04-12 10:36 UTC
